sudo: false
language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
cache: apt
addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - conda update --yes conda
install: 
 - conda install --yes python=$TRAVIS_PYTHON_VERSION pip 
 - pip install cython numpy scipy nose matplotlib psutil
 - pip install astropy
 - pip install  corner KMlogger emcee pathos
 #- pip install -r requirements.txt
 - pip install pep8 python-coveralls
# command to run tests
script:
 - coverage run --source=ExoSOFT setup.py test
after_success:
 - coveralls
notifications:
  email: false
